### ISSUE TITLE
Please help with this error

### ISSUE THREAD

**Issue by mineo7** [lwitzani/homebridgeStatusWidget#55] opened 2023-10-12 01:36 UTC
Exception Occurred
Error: Cannot parse response to an image.

**Comment by lwitzani** [comment] 2023-10-12 07:01
I have no chance to find anything out, if you only provide a single line of text containing an error message. You need to provide the context and how to reproduce the issue 👍🏻

**Comment by itsfelipeh** [comment] 2023-10-12 21:21
![Uploading IMG_4116.png…]()

**Comment by mineo7** [comment] 2023-10-13 02:07
Hi,
I was going to reply when I saw that mail, yes that's the same error message I get when I try to run the script
Here is some info on my setting;

Homebridge V1.6.1
Homebrdge-config-ui-x V4.50.6
Scriptable V1.7.11
IOS 17.0.3

Homebridge status widget downloaded using ScriptDude

When I try to run the script I get that error message

**Comment by lwitzani** [comment] 2023-10-13 06:01
Okay it might be some problem of iOS 17 or maybe the version of Scriptable is not yet perfectly compatible with iOs17. This happens a lot when people switch to a newer iOS version (there is always some random issue then 🤪). In the past these kind of problems where usually fixed by the developer of Scriptable or the Apple developers. 

i am not yet on iOS 17 so that is why i cannot reproduce the issue at the moment. I can have a look at this problem but it will take multiple days because i am on vacation right now 😬

**Comment by kolorfilm** [comment] 2023-10-14 12:38
I have the same problem. It seems it takes too long for the plug-in to answer, or Homebridge itself. I tried too creased the timeout setting, but this seems not to help.

**Comment by lwitzani** [comment] 2023-10-16 11:02
guys i have the solution. It was no problem with iOS 17 and also no problem with the Scriptable app.
The Github URL for the actual homebridge logo changed. 

Before, the logoUrl was this
`https://github.com/homebridge/branding/blob/master/logos/homebridge-silhouette-round-white.png?raw=true`

but now it needs to be this:
`https://raw.githubusercontent.com/homebridge/branding/latest/logos/homebridge-silhouette-round-white.png`

This is no problem for people who already downloaded the image once because the script saves the file in iCloud and then uses it from there. For people that set up the script the first time, they will face this problem. I was able to reproduce it by deleting my image from iCloud. 

**How can you fix it on your device?**
I pushed a commit where i changed the URL. You can update via Scriptdude or even manually switch out the URL (it's the logoUrl around line 49). Updating via Scriptdude will wipe all your changes in the script, so maybe make a backup of those if you have some (the URL and the credentials need to be entered again after updating via scriptdude). If it still does not work immediately then you probably need to set overwritePersistedConfig = true once because this URL is also persisted and reused and it needs to land in the persisted file that contains all the configurations as well. 

If you want to keep everything as it is and just want to switch the URL, then switch it in the script and also in the persisted config file in your iCloud files (if you already have one of those)

**Comment by kolorfilm** [comment] 2023-10-16 14:31
@lwitzani I updated the script and get now another error. 😅

_Expection Occured
Error: Base URL to machine not entered! Edit variable called hbServiceMachineBaseUrl_ 🤔 

I'm using an own config file `ownConfig.json`. The `hbServiceMachineBaseUrl` paramter defined there.

**Comment by lwitzani** [comment] 2023-10-16 14:40
@kolorfilm After updating, did you change the name in the script to point to your ownConfig.json again? (The variable configurationFileName at the top) 
When running the script inside of Scriptable this is still needed. When having the script set up as widget this should not be needed because here the name is provided via „USE_CONFIG:…“

Also, did you manually edit your json file? With editing i mean switching out the value of logoUrl ?

**Comment by kolorfilm** [comment] 2023-10-16 14:43
Ah thanks @lwitzani . Sorry I forgot to changed that back to my config. I had to change:

```
let configurationFileName = 'ownConfig.json'
const usePersistedConfiguration = true;
const overwritePersistedConfig = false;
```

That works!

**Comment by mineo7** [comment] 2023-10-17 01:32
Thanks a lot,I've got it working now,It’s awesome.Thanks again,Mineo Oshiro.On Oct 16, 2023, at 23:43, Michael Päßler ***@***.***> wrote:﻿
Ah thanks @lwitzani . Sorry I forgot to changed that back to my config. I had to change:
let configurationFileName = 'ownConfig.json'
const usePersistedConfiguration = true;
const overwritePersistedConfig = false;

That works!

**Closed** 2023-10-20 13:43 UTC
